### PR TITLE
Update POM

### PR DESCRIPTION
**Pull request by volosied**
Few changes:

maven-release-manager was stuck on the following line, so I updated it to version 2.5.3

`Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release-manager/2.2.1/maven-release-manager-2.2.1.pom`

I also had a lot of error the ones below. So I a profile to avoid them (errors turned into warnings). (code taken from https://github.com/iipc/openwayback/pull/139/files) 

```
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/model/RenderKitMeta.java:207: warning - @param argument "componentFamily" is not a parameter name.
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/qdox/_TagAttributes.java:35: warning - Tag @see: reference not found: org.apache.myfaces.view.facelets.tag.Tag
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/qdox/_TagAttributes.java:36: warning - Tag @see: reference not found: org.apache.myfaces.view.facelets.tag.TagAttributeImpl
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/qdox/QdoxHelper.java:161: warning - invalid usage of tag >
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/trinidad/parse/AccessibilityGuidelineBean.java:25: warning - invalid usage of tag <
[INFO] [ERROR] /Users/siedlecki/open-source/myfaces-build-tools/maven2-plugins/myfaces-builder-plugin/src/main/java/org/apache/myfaces/buildtools/maven2/plugin/builder/trinidad/parse/AccessibilityGuidelineBean.java:25: warning - invalid usage of tag >
```

Lastly, I updated scm to git. 

Please let me know of any feedback.

### CODE REVIEW

**Comment by volosied** [comment]
I believe I need to update the master branch so avoid the following error during the release dry run: 


```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project myfaces-builder-plugin: Cannot prepare the release because you have local modifications : 
[ERROR] [maven2-plugins/myfaces-builder-plugin/pom.xml:modified]
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by tandraschko** [comment]
looks good for me

**Comment by volosied** [comment]
More errors I encountered: 

```
(base) Volodymyrs-MBP:myfaces-builder-plugin siedlecki$ git clone https://gitbox.apache.org/repos/asf?p=myfaces.git
Cloning into 'asf?p=myfaces'...
fatal: repository 'https://gitbox.apache.org/repos/asf?p=myfaces.git/' not found
```

Instead, I'm using `https://gitbox.apache.org/repos/asf/myfaces.git` as the URL.

I had some other errors, so I changed the maven-release-plugin to version 2.2.2 instead.

**Comment by volosied** [comment]
@tandraschko  I made a few more edits, if you could take a quick look.

**Comment by tandraschko** [comment]
looks still good

**Pull request merged**
